import os
import sys
from dotenv import load_dotenv
from fpdf import FPDF 

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from workflows.langgraph_pipeline import build_workflow
from utils.metrics_tracker import tracker

def export_to_pdf(report_content, filename="Industrial_Analysis_Report.pdf"):
    """Converts the LLM text into a professional PDF layout."""
    pdf = FPDF()
    pdf.add_page()
    
    # Header: Title & Branding
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Industrial AI Architect: Operations Report", ln=True, align='C')
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(200, 10, txt="Generated by LangGraph Multi-Agent Pipeline", ln=True, align='C')
    pdf.ln(10) 
    
    # Text Cleanup for FPDF (Fixes the UnicodeEncodeError)
    clean_text = report_content.replace("**", "")
    
    # Replace common fancy unicode characters with standard ASCII equivalents
    unicode_replacements = {
        '\u2013': '-',   # en dash
        '\u2014': '-',   # em dash
        '\u2018': "'",   # left single quote
        '\u2019': "'",   # right single quote
        '\u201c': '"',   # left double quote
        '\u201d': '"',   # right double quote
        '\u2022': '-',   # bullet
        '\t': '    '     # replace tabs with spaces
    }
    
    for fancy_char, standard_char in unicode_replacements.items():
        clean_text = clean_text.replace(fancy_char, standard_char)
        
    # Final brute-force safety catch: replace any remaining unknown chars with a '?'
    clean_text = clean_text.encode('latin-1', 'replace').decode('latin-1')
    
    # Body: The Report
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 10, txt=clean_text)
    
    # Footer: Performance Metadata
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 10)
    pdf.cell(200, 10, txt="Pipeline Performance Summary:", ln=True)
    pdf.set_font("Arial", size=9)
    for metric in tracker.metrics:
        m_text = f"- {metric['agent_name']}: {metric['execution_time_seconds']}s | {metric['total_tokens']} tokens"
        pdf.cell(200, 8, txt=m_text, ln=True)
        
    pdf.output(filename)
    print(f"\n[Success] Visualized PDF report saved as: {filename}")

if __name__ == "__main__":
    load_dotenv()
    print("Initializing Industrial Multi-Agent Pipeline...")
    
    app = build_workflow()
    
    initial_state = {
        "file_paths": {},
        "sensor_summary": {},
        "iot_payloads": [],
        "parsed_logs": [],
        "ocr_result": {}, 
        "final_report": ""
    }
    
    print("Executing LangGraph DAG...")
    final_state = app.invoke(initial_state)
    
    report_text = final_state.get("final_report", "Report generation failed.")
    
    # Print 
    print("\n" + "="*50)
    print("FINAL MANUFACTURING REPORT")
    print("="*50)
    print(report_text)
    
    # Export as PDF 
    export_to_pdf(report_text)
    
    tracker.save_metrics("langgraph_industrial_demo/benchmark_metrics.json")
