"""
layer_1/agent_1c_tools.py — Agent 1C Deterministic Tools

Implements the programmatic tools that bookend the Agent 1C pipeline.
The bulk parser now purely converts unstructured text into standardized 
dictionaries based on the LLM's structural regex, leaving all semantic 
extraction and deduplication to Layer 2.
"""

import os
import re
from typing import Any, Dict


# ─────────────────────────────────────────────────────────────────────────────
# Tool 1 — Log Sampler (Stage 1)
# ─────────────────────────────────────────────────────────────────────────────

def extract_log_sample(file_path: str, num_lines: int = 20) -> Dict[str, Any]:
    """
    Reads the first N non-empty lines from a log or text-based signal file.
    This guarantees the LLM only consumes a tiny, constant amount of tokens
    regardless of the log file's total size.
    """
    if not os.path.exists(file_path):
        return {"error": f"File not found: {file_path}"}
        
    try:
        sample = []
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                clean_line = line.strip()
                if clean_line:  # Skip empty lines
                    sample.append(clean_line)
                if len(sample) >= num_lines:
                    break
        
        if not sample:
            return {"error": "File is empty or contains no readable text."}
            
        return {"sample_lines": sample}
        
    except Exception as exc:
        return {"error": f"Sampling failed: {exc}"}


# ─────────────────────────────────────────────────────────────────────────────
# Tool 2 — Bulk Log Standardizer (Stage 3)
# ─────────────────────────────────────────────────────────────────────────────

def standardize_logs_with_regex(file_path: str, regex_pattern: str) -> Dict[str, Any]:
    """
    Applies the LLM-generated structural regex to the entire file programmatically.
    Converts unstructured log lines into a clean, standard list of dictionaries 
    ready for Layer 2 reasoning. No entity deduplication is performed here.
    """
    if not os.path.exists(file_path):
        return {"error": f"File not found: {file_path}"}
        
    try:
        compiled_regex = re.compile(regex_pattern)
        parsed_records = []
        unparsed_count = 0
        total_lines = 0
        
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                clean_line = line.strip()
                if not clean_line:
                    continue
                    
                total_lines += 1
                match = compiled_regex.match(clean_line)
                
                if match:
                    parsed_records.append(match.groupdict())
                else:
                    unparsed_count += 1

        return {
            "status": "success",
            "total_lines_processed": total_lines,
            "parsed_records_count": len(parsed_records),
            "unparsed_count": unparsed_count,
            "data": parsed_records
        }
        
    except re.error as e:
        return {"error": f"Invalid regex pattern generated by LLM: {e}"}
    except Exception as exc:
        return {"error": f"Bulk parsing failed: {exc}"}